using Microsoft.EntityFrameworkCore.Migrations;

namespace DesignManagement.Migrations
{
    public partial class AutogeneratedIdForProjectCustom : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
             migrationBuilder.Sql($"SET IDENTITY_INSERT dbo.Projects ON;");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql($"SET IDENTITY_INSERT dbo.Projects OFF;");
        }
    }
}
